server:
  host: 0.0.0.0
  port: 8080
  mode: debug # debug, release, test
  jwt_secret: your_jwt_secret_key_here
  jwt_expire: 7200 # seconds
  jwt_issuer: blog_api
  jwt_refresh_expire: 604800 # 7 days in seconds
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
    exposed_headers: ["Content-Length"]
    allow_credentials: true
    max_age: 86400

database:
  host: localhost
  port: 5432
  username: blog_test
  password: blogtestpass
  dbname: blog
  sslmode: disable
  timezone: Asia/Shanghai
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # seconds

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5 # seconds
  read_timeout: 3 # seconds
  write_timeout: 3 # seconds

log:
  level: debug # debug, info, warn, error, dpanic, panic, fatal
  format: console # console, json
  output_paths: ["stdout", "logs/server.log"]
  error_output_paths: ["stderr", "logs/error.log"]
  max_size: 100 # MB
  max_age: 30 # days
  max_backups: 10
  compress: true
  local_time: true

upload:
  max_size: 10 # MB
  allow_types: ["image/jpeg", "image/png", "image/gif", "application/pdf"]
  save_path: "uploads"
  url_prefix: "/uploads/"
  storage_type: local # local, s3

swagger:
  enabled: true
  title: "博客系统API"
  description: "博客系统后端API文档"
  version: "1.0"
  host: "localhost:8080"
  base_path: "/"